#!/bin/bash
#Write a program that takes the name of a file as a parameter and, if the file has a .py extension, removes lines from it that are single-line comments (beginning with the # symbol).

if [ "$#" -ne 1 ]
then
	echo "Usage: [$0] filename"
	exit 1
fi

if [ ! -f "$1" ]
then
	echo "[$1] is not a file"
	exit 2
fi

if [ "${1: -3}" != ".py" ]
then
	echo "[$1] is not a python file"
	exit 3
fi

sed -i '/^#/d' "$1"